### PR TITLE
Building documentation via sphinx

### PR DESCRIPTION
**Pull request by maumueller**
This PR adds support to build the documentation via sphinx. The goal is to share the documentation as can be seen on https://itualgs4.readthedocs.io/en/sphinx-build/.

### CODE REVIEW

**Comment by maumueller** [comment]
The main problem is that there are still "some" problems with the docstrings.


```
$pydocstyle |  wc -l                                                                                                                                                                                                                
2838

$pydocstyle | grep "D205" | wc -l                                                                                                                                                                                                   
398
```

The latter will give formatting problems, as can be seen for the red-black tree documentation https://itualgs4.readthedocs.io/en/sphinx-build/source/itu.algs4.searching.html.

**Comment by holgerdell** [comment]
Ist das fertig? Falls ja, squash and commit

**Comment by maumueller** [comment]
Yes, but the linter seems to fail. This doesn't seem to be connected to #4 or #5.

**Comment by holgerdell** [comment]
Ja das war meine Schuld (die Version von isort auf github war neuer als meine lokale). Nach einem force-push ist das Problem jetzt gelöst, jetzt könntest es mit einem rebase versuchen.

**Pull request merged**
